language: php
os:
  - linux
dist: bionic

php:
  - 7.4
  - 8.0
  - 8.1.0

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.4.*

before_script:
  - phpenv config-add myphp.ini
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install --prefer-dist --no-interaction
  - ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
  - ./src/BeSimple/SoapClient/Tests/bin/axis.sh

script:
  - SYMFONY_DEPRECATIONS_HELPER="max[indirect]=6" bin/simple-phpunit --coverage-text

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change
    on_failure: always
