services:
  app:
    build: .
    image: NatLibFi/besimplesoap
    container_name: nlf_besimplesoap
    environment:
      SYMFONY_PHPUNIT_VERSION: '9.5'
      COMPOSER_ALLOW_SUPERUSER: 1
      JAVA_HOME: /usr/bin
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:rw
